# Generated by Django 5.1.5 on 2025-01-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_update', '0002_remove_st_img_class_st_img_course_st_img_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_img',
            name='course',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts'), ('Business', 'Business'), ('Health', 'Health'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
